# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84ad089ad976918ea3afaf36b79b1328db7bf386da9d6a4fd88d03b9403507e51a52370f938477327138a70b6ea9ac1d7fc4f7352e20669b50d4b9a4d899cf91

test:
  secret_key_base: cb09f682248e30a1f78c7cfd9dc790d020bd92c68d1246bb0b6ef2b8401896a4af4e2e45a867cb042994a0167be4785831b39bf75b8c2ac6dd72a2ac1868e7b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
